kumuluzee:
  name: e-scooter-catalog
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  datasources:
    - jndi-name: jdbc/EscooterCatalogDS
      connection-url: jdbc:postgresql://localhost:5432/escooter
      username: dbuser
      password: postgres
      max-pool-size: 20